version: '3'

services:
  db:
    image: mariadb
    container_name: dmoj-db
    restart: unless-stopped
    env_file: .docker/env/db.env
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: dmoj-redis
    restart: unless-stopped

  site:
    build:
      context: .
      dockerfile: .docker/site/Dockerfile
    entrypoint: /dmoj/boot.sh
    command: ["uwsgi", "--ini", "../uwsgi.ini"]
    container_name: dmoj-site
    restart: unless-stopped
    env_file: .docker/env/django.env
    volumes:
      - app_static:/dmoj/static
      - ./log:/dmoj/log
      - .docker/volumes/problems:/dmoj/problems
      - .docker/volumes/media:/dmoj/media
    depends_on:
      - db
      - redis
      - bridged
      - events

  bridged:
    build:
      context: .
      dockerfile: .docker/site/Dockerfile
    command: ["python", "manage.py", "runbridged"]
    container_name: dmoj-bridged
    restart: unless-stopped
    env_file: .docker/env/django.env
    volumes:
      - ./log:/dmoj/log
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: .docker/site/Dockerfile
    command: ["celery", "-A", "dmoj_celery", "worker"]
    container_name: dmoj-celery
    restart: unless-stopped
    env_file: .docker/env/django.env
    volumes:
      - ./log:/dmoj/log
    depends_on:
      - redis
      - db

  events:
    build:
      context: .
      dockerfile: .docker/events/Dockerfile
    container_name: dmoj-events
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: dmoj-nginx
    restart: unless-stopped
    volumes:
      - app_static:/dmoj/static:ro
      - ./log:/dmoj/log
      - .docker/volumes/media:/dmoj/media
      - .docker/volumes/lib:/dmoj/lib
    ports:
      - "8002:80"
    depends_on:
      - site
      - events

volumes:
  db_data:
  app_static:
